// Generated by Wrangler on Thu Sep 05 2024 23:07:18 GMT-0500 (hora estándar de Perú)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	proxy_reverse_webflow: KVNamespace;
	WEBFLOW_DOMAIN: "https://hapi-519526.webflow.io/";
}
